[package]
name = "zng-unique-id"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-unique-id"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["named", "bytemuck" ]
named = ["zng-txt", "parking_lot"]
bytemuck = []

[dependencies]
zng-txt = { path = "../zng-txt", optional = true }
parking_lot = { version = "0.12", optional = true }

rayon = "1"
hashbrown = { version = "0.14", features = ["rayon"] }
tracing = "0.1"
paste = "1"