[package]
name = "zng-ext-config"
version = "0.2.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-ext-config"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
yaml = ["dep:serde_yaml", "zng-ext-fs-watcher/yaml"]
toml = ["dep:toml", "zng-ext-fs-watcher/toml"]
ron = ["dep:ron", "zng-ext-fs-watcher/ron"]

[dependencies]
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-app = { path = "../zng-app", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.0" }
zng-txt = { path = "../zng-txt", version = "0.2.0" }
zng-task = { path = "../zng-task", version = "0.2.0" }
zng-clone-move = { path = "../zng-clone-move", version = "0.2.0" }
zng-unique-id = { path = "../zng-unique-id", version = "0.2.0" }
zng-ext-fs-watcher = { path = "../zng-ext-fs-watcher", version = "0.2.0", features = [
    "json",
] }

tracing = "0.1"
bytemuck = "1"
indexmap = { version = "2", features = ["serde"] }
atomic = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = { version = "0.8", optional = true, features = ["preserve_order"] }
ron = { version = "0.8", optional = true, features = ["indexmap"] }
serde_yaml = { version = "0.9", optional = true }
