[package]
name = "zng-wgt-undo-history"
version = "0.5.0"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_undo_history"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.7.0" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.6.0" }
zng-wgt-button = { path = "../zng-wgt-button", version = "0.6.0" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.6.0" }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.6.0" }
zng-wgt-stack = { path = "../zng-wgt-stack", version = "0.5.0" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.5.0" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.4.0" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.4.0" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.4.0" }
zng-ext-undo = { path = "../zng-ext-undo", version = "0.4.0" }
zng-ext-input = { path = "../zng-ext-input", version = "0.7.0" }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.7.0" }
