[package]
name = "zng-wgt-button"
version = "0.4.21"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_button"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-var = { path = "../zng-var", version = "0.5.9" }
zng-app = { path = "../zng-app", version = "0.13.4" }
zng-ext-font = { path = "../zng-ext-font", version = "0.4.12" }
zng-wgt = { path = "../zng-wgt", version = "0.5.4" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.3.18" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.3.28" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.40" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.38" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.38" }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.2.38" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.4.21" }
zng-wgt-tooltip = { path = "../zng-wgt-tooltip", version = "0.4.21" }
