[package]
name = "zng-ext-l10n-proc-macros"
version = "0.4.0"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_l10n_proc_macros"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", default-features = false }
syn = { version = "2.0", default-features = false, features = ["full", "visit", "extra-traits", "derive"] }
quote = { version = "1.0", default-features = false }

fluent-syntax = { version = "0.12", default-features = false }
unic-langid = { version = "0.9", default-features = false }
