[package]
name = "zng-example-window"
version = "0.0.0"
publish = false
edition = "2024"

[dependencies]
zng = { path = "../../crates/zng", features = ["view_prebuilt", "inspector", "material_icons"] }
tracing = "0.1"