[workspace]
members = [
    # view:
    "zero-ui-view-api", 
    "zero-ui-view", 
    "zero-ui-view-prebuilt", 

    # main:
    "zero-ui-proc-macros", 
    "zero-ui-core", 
    "zero-ui",
    "zero-ui-material-icons",

    # examples:
    "examples",
    "examples/util",

    # tests:
    "tests",
    "tests/build",
]

exclude = [
    "dependencies/webrender"
]

[profile.dev]
debug = 1

[profile.release-lto]
inherits = "release"
lto = true

[profile.prebuild]
inherits = "release-lto"