[package]
name = "zng-txt"
version = "0.2.3"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_txt"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]


[dependencies]
serde = "1.0"
