[package]
name = "zng-l10n-scraper"
version = "0.2.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-l10n-scraper"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
rayon = "1"
glob = "0.3"
rustc_lexer = "0.1"
clap = { version = "4", features = ["derive"] }
fluent-pseudo = "0.3"
