[package]
name = "zng-wgt-toggle"
version = "0.3.16"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_toggle"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.4.9" }
zng-wgt-button = { path = "../zng-wgt-button", version = "0.4.6" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.3.6" }
zng-wgt-layer = { path = "../zng-wgt-layer", version = "0.3.16" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.26" }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.4.16" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.26" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.26" }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.2.26" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.4.6" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.26" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.3.16" }
zng-wgt-transform = { path = "../zng-wgt-transform", version = "0.2.26" }
zng-ext-input = { path = "../zng-ext-input", version = "0.5.14" }
zng-ext-font = { path = "../zng-ext-font", version = "0.3.22" }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.5.6" }
zng-var = { path = "../zng-var", version = "0.4.10" }

parking_lot = "0.12"
tracing = "0.1"
