[package]
name = "zng-wgt-toggle"
version = "0.11.4"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_toggle"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.13.4", default-features = false }
zng-wgt-button = { path = "../zng-wgt-button", version = "0.12.4", default-features = false }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.12.4", default-features = false }
zng-wgt-layer = { path = "../zng-wgt-layer", version = "0.11.4", default-features = false }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.10.4", default-features = false }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.12.4", default-features = false }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.10.4", default-features = false }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.10.4", default-features = false }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.10.4", default-features = false }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.12.4", default-features = false }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.10.4", default-features = false }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.11.4", default-features = false }
zng-wgt-transform = { path = "../zng-wgt-transform", version = "0.10.4", default-features = false }
zng-ext-input = { path = "../zng-ext-input", version = "0.13.4", default-features = false }
zng-ext-font = { path = "../zng-ext-font", version = "0.12.4", default-features = false }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.13.4", default-features = false }
zng-var = { path = "../zng-var", version = "0.12.1", default-features = false }
zng-ext-window = { path = "../zng-ext-window", version = "0.11.4", default-features = false }

parking_lot = { version = "0.12", default-features = false }
tracing = { version = "0.1", default-features = false }
hashbrown = { version = "0.16", default-features = false }
