[package]
name = "zng-ext-single-instance"
version = "0.4.9"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_single_instance"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-env = { path = "../zng-env", version = "0.3.9" }
zng-app = { path = "../zng-app", version = "0.14.9" }
zng-txt = { path = "../zng-txt", version = "0.2.8" }
zng-task = { path = "../zng-task", version = "0.4.18" }
zng-ext-fs-watcher = { path = "../zng-ext-fs-watcher", version = "0.3.9" }

parking_lot = "0.12"
single-instance = "0.3"
tracing = "0.1"
serde_json = "1.0"
dunce = "1.0"
