[package]
name = "zng-state-map"
version = "0.2.1"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_state_map"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-unique-id = { path = "../zng-unique-id", version = "0.2.1" }

bytemuck = { version = "1" }
pretty-type-name = "1"
