[package]
name = "zng-wgt-scroll"
version = "0.2.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-scroll"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]
debug_default = []
dyn_closure = []

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.0" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.0" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.0" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.0" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.2.0" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.0" }
zng-app = { path = "../zng-app", version = "0.2.0" }
zng-ext-window = { path = "../zng-ext-window", version = "0.2.0" }
zng-ext-input = { path = "../zng-ext-input", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.0" }
zng-color = { path = "../zng-color", version = "0.2.0" }

serde = { version = "1", features = ["derive"] }
atomic = "0.6"
bitflags = { version = "2", features = ["serde", "bytemuck"] }
bytemuck = { version = "1", features = ["derive"] }
euclid = "0.22"
parking_lot = "0.12"
tracing = "0.1"
