[package]
name = "zng-ext-undo"
version = "0.10.5"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_undo"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.4.0", default-features = false }
zng-app-context = { path = "../zng-app-context", version = "0.11.2", default-features = false }
zng-app = { path = "../zng-app", version = "0.21.5", default-features = false }
zng-wgt = { path = "../zng-wgt", version = "0.13.5", default-features = false }
zng-var = { path = "../zng-var", version = "0.12.2", default-features = false }
zng-txt = { path = "../zng-txt", version = "0.5.2", default-features = false }
zng-state-map = { path = "../zng-state-map", version = "0.9.2", default-features = false }
zng-ext-input = { path = "../zng-ext-input", version = "0.13.5", default-features = false }

atomic = { version =  "0.6", default-features = false, features = ["fallback"] }
parking_lot = { version = "0.12", default-features = false }

[dev-dependencies]
zng-app = { path = "../zng-app", version = "0.21.5", default-features = false, features = ["test_util"] }
