[package]
name = "zng-ext-undo"
version = "0.3.9"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_undo"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.2.5" }
zng-app-context = { path = "../zng-app-context", version = "0.5.14" }
zng-app = { path = "../zng-app", version = "0.14.9" }
zng-wgt = { path = "../zng-wgt", version = "0.6.9" }
zng-var = { path = "../zng-var", version = "0.5.16" }
zng-txt = { path = "../zng-txt", version = "0.2.8" }
zng-state-map = { path = "../zng-state-map", version = "0.3.8" }
zng-ext-input = { path = "../zng-ext-input", version = "0.6.9" }

atomic = "0.6"
parking_lot = "0.12"
