[package]
name = "zng-wgt-webrender-debug"
version = "0.2.2"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_webrender_debug"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app = { path = "../zng-app", version = "0.2.2" }
zng-wgt = { path = "../zng-wgt", version = "0.2.2" }
zng-ext-window = { path = "../zng-ext-window", version = "0.2.2" }
zng-view-api = { path = "../zng-view-api", version = "0.2.2" }

webrender-api = { git = "https://github.com/zng-ui/zng-webrender.git", package = "zng-webrender-api", version = "0.62.1" }
serde = "1"
bitflags = { version = "2", features = ["serde", "bytemuck"] }
tracing = "0.1"
