[package]
name = "zng-wgt-stack"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-stack"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]
debug_default = []
dyn_closure = []

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.1.0" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.1.0" }
zng-app = { path = "../zng-app", version = "0.1.0" }
zng-layout = { path = "../zng-layout", version = "0.1.0" }
zng-var = { path = "../zng-var", version = "0.1.0" }

euclid = "0.22"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"