[package]
name = "zng-wgt-shortcut"
version = "0.5.3"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_panel"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.13.3", default-features = false }
zng-wgt-wrap = { path = "../zng-wgt-wrap", version = "0.11.3", default-features = false }
zng-app = { path = "../zng-app", version = "0.21.3", default-features = false }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.12.3", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.18.1", default-features = false }
zng-txt = { path = "../zng-txt", version = "0.5.0", default-features = false }
zng-ext-font = { path = "../zng-ext-font", version = "0.12.3", default-features = false }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.10.3", default-features = false }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.12.3", default-features = false }
zng-color = { path = "../zng-color", version = "0.11.2", default-features = false }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.13.3", default-features = false }
