[package]
name = "zng-wgt-ansi-text"
version = "0.6.7"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_ansi_text"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.8.6" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.7.7" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.5.6" }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.5.6" }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.7.6" }
zng-wgt-stack = { path = "../zng-wgt-stack", version = "0.6.6" }
zng-ext-font = { path = "../zng-ext-font", version = "0.7.6" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.5.6" }

serde = { version = "1.0", features = ["derive"] }
