[package]
name = "zng-ext-input"
version = "0.3.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_input"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app-context = { path = "../zng-app-context", version = "0.3.0" }
zng-clone-move = { path = "../zng-clone-move", version = "0.2.2" }
zng-view-api = { path = "../zng-view-api", version = "0.2.4" }
zng-app = { path = "../zng-app", version = "0.3.0" }
zng-txt = { path = "../zng-txt", version = "0.2.3" }
zng-var = { path = "../zng-var", version = "0.2.4" }
zng-layout = { path = "../zng-layout", version = "0.2.4" }
zng-handle = { path = "../zng-handle", version = "0.2.2" }
zng-state-map = { path = "../zng-state-map", version = "0.2.3" }
zng-unique-id = { path = "../zng-unique-id", version = "0.2.3" }
zng-ext-window = { path = "../zng-ext-window", version = "0.2.4" }

tracing = "0.1"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
bitflags = { version = "2.5", features = ["serde", "bytemuck"] }
atomic = "0.6"
