[package]
name = "zng-wgt"
version = "0.2.4"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]

# Signal the build script to enable the `"dyn_*"`, `"inspector"` and `"trace_widget"` features for debug builds.
#
# Enabled by default.
debug_default = ["zng-var/debug_default"]

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = ["zng-var/dyn_closure"]

# Enable web tasks.
http = ["zng-task/http"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.2.2" }
zng-app = { path = "../zng-app", version = "0.3.0" }
zng-color = { path = "../zng-color", version = "0.2.4" }
zng-app-context = { path = "../zng-app-context", version = "0.3.0" }
zng-var = { path = "../zng-var", version = "0.2.4" }
zng-state-map = { path = "../zng-state-map", version = "0.2.3" }
zng-layout = { path = "../zng-layout", version = "0.2.4" }
zng-task = { path = "../zng-task", version = "0.2.4" }
zng-txt = { path = "../zng-txt", version = "0.2.3" }
zng-unique-id = { path = "../zng-unique-id", version = "0.2.3" }

paste = "1.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
pretty-type-name = "1.0"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "doc/html-in-header.html"]
