[package]
name = "zng-wgt-size-offset"
version = "0.10.5"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_size_offset"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.13.5", default-features = false }

euclid = { version = "0.22", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
