[package]
name = "zng-ext-font"
version = "0.3.3"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_font"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
test_util = ["zng-app/test_util"]
hyphenation_embed_all = ["hyphenation/embed_all"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.2.3" }
zng-app-context = { path = "../zng-app-context", version = "0.3.1" }
zng-app = { path = "../zng-app", version = "0.3.3" }
zng-txt = { path = "../zng-txt", version = "0.2.4" }
zng-view-api = { path = "../zng-view-api", version = "0.2.7" }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.3.3" }
zng-var = { path = "../zng-var", version = "0.2.5" }
zng-task = { path = "../zng-task", version = "0.2.5" }
zng-layout = { path = "../zng-layout", version = "0.2.5" }
zng-color = { path = "../zng-color", version = "0.2.7" }

serde = "1.0"
unicase = "2.7"
font-kit = "0.13"
harfbuzz_rs = "2.0"
parking_lot = "0.12"
byteorder = "1.5"
icu_properties = "1.4"
bitflags = { version = "2.5", features = ["serde", "bytemuck"] }
tracing = "0.1"
paste = "1.0"
num_enum = "0.7"
hyphenation = "0.8"
regex = "1.10"
unicode-bidi = "0.3"
unicode-linebreak = "0.1"
unicode-segmentation = "1.11"
unic-langid = "0.9"
smallvec = { version = "1.13", features = ["const_new", "serde"] }
hashbrown = "0.14"
pathfinder_geometry = "0.5"

[package.metadata.docs.rs]
all-features = true
