[package]
name = "zng-wgt-progress"
version = "0.4.10"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_progress"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.8.9" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.7.10" }
zng-ext-font = { path = "../zng-ext-font", version = "0.7.9" }
zng-layout = { path = "../zng-layout", version = "0.4.5" }
zng-app = { path = "../zng-app", version = "0.16.9" }
zng-task = { path = "../zng-task", version = "0.6.7" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.6.9" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.7.9" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.5.9" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.5.9" }
zng-var = { path = "../zng-var", version = "0.7.5" }

tracing = "0.1"
