[package]
name = "zng-wgt-progress"
version = "0.8.1"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_progress"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.12.1", default-features = false }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.11.1", default-features = false }
zng-ext-font = { path = "../zng-ext-font", version = "0.11.1", default-features = false }
zng-layout = { path = "../zng-layout", version = "0.8.1", default-features = false }
zng-app = { path = "../zng-app", version = "0.20.1", default-features = false }
zng-task = { path = "../zng-task", version = "0.10.1", default-features = false }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.10.1", default-features = false }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.11.1", default-features = false }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.9.1", default-features = false }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.9.1", default-features = false }
zng-var = { path = "../zng-var", version = "0.11.1", default-features = false }
zng-wgt-image = { path = "../zng-wgt-image", version = "0.10.1", default-features = false }
zng-ext-image = { path = "../zng-ext-image", version = "0.9.1", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.17.1", default-features = false }

tracing = { version = "0.1", default-features = false }
