[package]
name = "zng-wgt-progress"
version = "0.3.30"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_progress"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.5.3" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.4.20" }
zng-ext-font = { path = "../zng-ext-font", version = "0.4.11" }
zng-layout = { path = "../zng-layout", version = "0.2.29" }
zng-app = { path = "../zng-app", version = "0.13.3" }

tracing = "0.1"
