[package]
name = "zng-var"
version = "0.2.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-var"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]

# Signal the build script to enable the `dyn_*` features for debug builds.
#
# Enabled by default.
debug_default = []

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = []

[dependencies]
zng-var-proc-macros = { path = "../zng-var-proc-macros", version = "0.2.0" }

zng-txt = { path = "../zng-txt", version = "0.2.0" }
zng-unit = { path = "../zng-unit", version = "0.2.0" }
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-time = { path = "../zng-time", version = "0.2.0" }
zng-clone-move = { path = "../zng-clone-move", version = "0.2.0" }
zng-handle = { path = "../zng-handle", version = "0.2.0" }

bitflags = { version = "2", features = ["serde"] }
bytemuck = { version = "1", features = ["derive"] }
parking_lot = "0.12"
tracing = "0.1"
take_mut = "0.2"
pretty-type-name = "1"
