[package]
name = "zng-ext-input"
version = "0.12.1"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_input"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
# Enable drag&drop.
drag_drop = []

[dependencies]
zng-app-context = { path = "../zng-app-context", version = "0.10.0", default-features = false }
zng-clone-move = { path = "../zng-clone-move", version = "0.4.0", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.17.1", default-features = false }
zng-app = { path = "../zng-app", version = "0.20.1", default-features = false }
zng-txt = { path = "../zng-txt", version = "0.5.0", default-features = false }
zng-var = { path = "../zng-var", version = "0.11.1", default-features = false }
zng-layout = { path = "../zng-layout", version = "0.8.1", default-features = false }
zng-handle = { path = "../zng-handle", version = "0.4.0", default-features = false }
zng-state-map = { path = "../zng-state-map", version = "0.8.0", default-features = false }
zng-unique-id = { path = "../zng-unique-id", version = "0.9.0", default-features = false }
zng-ext-window = { path = "../zng-ext-window", version = "0.10.1", default-features = false }

tracing = { version = "0.1", default-features = false, features = ["std"] }
parking_lot = { version = "0.12", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
bitflags = { version = "2.5", default-features = false, features = ["serde", "bytemuck"] }
atomic = { version = "0.6", default-features = false }
uuid = { version = "1.3", default-features = false, features = ["v4", "js"] }
