[package]
name = "zng-wgt-input"
version = "0.2.29"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_input"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.4.12" }
zng-wgt-transform = { path = "../zng-wgt-transform", version = "0.2.29" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.29" }
zng-ext-input = { path = "../zng-ext-input", version = "0.5.17" }
zng-ext-window = { path = "../zng-ext-window", version = "0.3.19" }
zng-app = { path = "../zng-app", version = "0.9.9" }
zng-view-api = { path = "../zng-view-api", version = "0.7.2" }
zng-ext-clipboard = { path = "../zng-ext-clipboard", version = "0.2.29" }
