[package]
name = "zng-wgt-input"
version = "0.10.1"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_input"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
# Enable drag&drop.
drag_drop = ["zng-ext-input/drag_drop"]
# Enable image cursor.
image = ["zng-ext-window/image"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.13.1", default-features = false }
zng-wgt-transform = { path = "../zng-wgt-transform", version = "0.10.1", default-features = false }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.10.1", default-features = false }
zng-ext-input = { path = "../zng-ext-input", version = "0.13.1", default-features = false }
zng-ext-window = { path = "../zng-ext-window", version = "0.11.1", default-features = false }
zng-app = { path = "../zng-app", version = "0.21.1", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.18.0", default-features = false }
zng-ext-clipboard = { path = "../zng-ext-clipboard", version = "0.10.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
