[package]
name = "zng-ext-svg"
version = "0.9.4"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_svg"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app = { path = "../zng-app", version = "0.21.4", default-features = false }
zng-ext-image = { path = "../zng-ext-image", version = "0.10.4", default-features = false }
zng-txt = { path = "../zng-txt", version = "0.5.1", default-features = false }
zng-unit = { path = "../zng-unit", version = "0.5.3", default-features = false }
zng-task = { path = "../zng-task", version = "0.11.2", default-features = false }
zng-var = { path = "../zng-var", version = "0.12.0", default-features = false }
zng-env = { path = "../zng-env", version = "0.9.1", default-features = false }

resvg = { version = "0.45", default-features = false }
tracing = { version = "0.1", default-features = false }

[package.metadata.docs.rs]
all-features = true
