[package]
name = "zng-wgt-undo"
version = "0.9.2"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_undo"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.12.2", default-features = false }
zng-ext-undo = { path = "../zng-ext-undo", version = "0.9.2", default-features = false }
