[package]
name = "zng-unique-id"
version = "0.3.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_unique_id"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["named"]
# Enable associated names for ID types.
named = ["dep:zng-txt", "dep:parking_lot"]

[dependencies]
zng-txt = { path = "../zng-txt", version = "0.2.6", optional = true }
parking_lot = { version = "0.12", optional = true }

rayon = "1.10"
hashbrown = { version = "0.14", features = ["rayon"] }
tracing = "0.1"
paste = "1.0"

[package.metadata.docs.rs]
all-features = true
