[package]
name = "zng-wgt-image"
version = "0.3.25"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_image"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.4.17" }
zng-app = { path = "../zng-app", version = "0.12.1" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.34" }
zng-ext-image = { path = "../zng-ext-image", version = "0.2.33" }
zng-ext-window = { path = "../zng-ext-window", version = "0.3.24" }
zng-wgt-window = { path = "../zng-wgt-window", version = "0.5.15" }
zng-wgt-stack = { path = "../zng-wgt-stack", version = "0.3.24" }

serde = { version = "1.0", features = ["derive"] }
