[package]
name = "zng-wgt-panel"
version = "0.4.12"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_panel"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.6.9" }
zng-wgt-wrap = { path = "../zng-wgt-wrap", version = "0.4.12" }
zng-app = { path = "../zng-app", version = "0.14.9" }
