# cargo about generate -c .cargo/about.toml --format json --workspace --all-features

accepted = [
    "Apache-2.0",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "Apache-2.0 WITH LLVM-exception",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
filter-noassertion = true
private = { ignore = true }