[advisories]
ignore = [
    # `paste` is unmaintained
    #
    # already replaced in project crates, `image` dependency still use it:
    #
    # ├── rav1e 0.7.1 - already fixed (0.8)
    # └── ravif 0.11.11 - already updated
    #     └── image 0.25.5 - pending
    #         ├── zng-view 0.8.0
    #         └── arboard 3.4.1
    #             └── zng-view 0.8.0
    #
    # remove this ignore when all dependencies are fixes
    "RUSTSEC-2024-0436",
]