[env]
DO_CMD = "cargo do"

[alias]
do = ["run", "--manifest-path", "tools/cargo-do/Cargo.toml", "--release", "--quiet", "--"]

[build]
# false positives in 1.92
# see https://github.com/rust-lang/rust/issues/149889
rustflags = ["-A", "unused_assignments"]