[package]
name = "zng-wgt-window"
version = "0.2.5"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_window"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]
debug_default = ["zng-wgt/debug_default"]
dyn_closure = ["zng-wgt/dyn_closure"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.4" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.2.4" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.4" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.2.5" }
zng-app = { path = "../zng-app", version = "0.3.0" }
zng-ext-window = { path = "../zng-ext-window", version = "0.2.4" }
zng-ext-config = { path = "../zng-ext-config", version = "0.2.4", default-features = false }
zng-ext-input = { path = "../zng-ext-input", version = "0.3.0" }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.3.0" }
zng-var = { path = "../zng-var", version = "0.2.4" }
zng-color = { path = "../zng-color", version = "0.2.4" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.4" }
zng-wgt-layer = { path = "../zng-wgt-layer", version = "0.2.4" }

serde = { version = "1.0", features = ["derive"] }
paste = "1.0"
parking_lot = "0.12"
euclid = "0.22"
