[package]
name = "zng-wgt-slider"
version = "0.1.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_slider"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-var = { path = "../zng-var", version = "0.5.9" }
zng-wgt = { path = "../zng-wgt", version = "0.5.5" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.3.29" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.41" }
zng-ext-input = { path = "../zng-ext-input", version = "0.5.29" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.4.1" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.39" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.39" }

parking_lot = "0.12"
tracing = "0.1"
