[package]
name = "zng-wgt-layer"
version = "0.11.4"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_layer"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
# Enable accurate cursor image hot-spot anchoring.
image = ["zng-ext-window/image"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.13.4", default-features = false }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.12.4", default-features = false }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.11.4", default-features = false }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.10.4", default-features = false }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.10.4", default-features = false }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.10.4", default-features = false }
zng-ext-window = { path = "../zng-ext-window", version = "0.11.4", default-features = false }
zng-app = { path = "../zng-app", version = "0.21.4", default-features = false }
zng-var = { path = "../zng-var", version = "0.12.1", default-features = false }
zng-ext-input = { path = "../zng-ext-input", version = "0.13.4", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.18.2", default-features = false }

parking_lot = { version = "0.12", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing = { version = "0.1", default-features = false }
