[package]
name = "zng-wgt-layer"
version = "0.4.9"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_layer"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.6.9" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.5.9" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.4.9" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.3.9" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.3.9" }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.3.9" }
zng-ext-window = { path = "../zng-ext-window", version = "0.4.9" }
zng-app = { path = "../zng-app", version = "0.14.9" }
zng-var = { path = "../zng-var", version = "0.5.16" }
zng-ext-input = { path = "../zng-ext-input", version = "0.6.9" }
zng-view-api = { path = "../zng-view-api", version = "0.11.6", default-features = false }

parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
