[package]
name = "zng-wgt-webrender-debug"
version = "0.11.4"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_webrender_debug"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app = { path = "../zng-app", version = "0.21.4", default-features = false }
zng-wgt = { path = "../zng-wgt", version = "0.13.4", default-features = false }
zng-ext-window = { path = "../zng-ext-window", version = "0.11.4", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.18.2", default-features = false }

# path = "../../../zng-webrender/webrender_api" for testing webrender updates
webrender-api = { package = "zng-webrender-api", version = "0.66.0", default-features = false }

serde = { version = "1.0", default-features = false }
bitflags = { version = "2.5", default-features = false, features = ["serde", "bytemuck"] }
tracing = { version = "0.1", default-features = false }
