[package]
name = "zng-wgt-container"
version = "0.5.9"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_container"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.6.9" }
zng-app = { path = "../zng-app", version = "0.14.9" }

serde = { version = "1.0", features = ["derive"] }
