[package]
name = "zng-ext-clipboard"
version = "0.2.20"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_clipboard"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app-context = { path = "../zng-app-context", version = "0.5.3" }
zng-app = { path = "../zng-app", version = "0.8.1" }
zng-var = { path = "../zng-var", version = "0.4.6" }
zng-view-api = { path = "../zng-view-api", version = "0.5.5" }
zng-txt = { path = "../zng-txt", version = "0.2.7" }
zng-ext-image = { path = "../zng-ext-image", version = "0.2.20" }
zng-wgt = { path = "../zng-wgt", version = "0.4.3" }

tracing = "0.1"
