[package]
name = "zng-ext-clipboard"
version = "0.10.3"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_clipboard"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app-context = { path = "../zng-app-context", version = "0.11.0", default-features = false }
zng-app = { path = "../zng-app", version = "0.21.3", default-features = false }
zng-var = { path = "../zng-var", version = "0.12.0", default-features = false }
zng-view-api = { path = "../zng-view-api", version = "0.18.1", default-features = false }
zng-txt = { path = "../zng-txt", version = "0.5.0", default-features = false }
zng-ext-image = { path = "../zng-ext-image", version = "0.10.3", default-features = false }
zng-wgt = { path = "../zng-wgt", version = "0.13.3", default-features = false }
zng-task = { path = "../zng-task", version = "0.11.1", default-features = false }

tracing = { version = "0.1", default-features = false, features = ["std"] }
