[package]
name = "zng-app"
version = "0.2.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-app"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["ipc", "debug_default"]

# Enables pre-build views and connecting to views running in another process.
# 
# Enabled by default.
ipc = ["zng-view-api/ipc"]
# Enable the `dyn_*`, `inspector` features for debug builds only.
#
# Enabled by default.
debug_default = ["zng-var/debug_default", "zng-app-context/dyn_closure"]

# Use dynamic dispatch at the node level by placing each property node in a `BoxedUiNode` and enabling `UiNode::cfg_boxed`.
#
# This speeds-up compilation time at the cost of runtime.
dyn_node = []

# Instrument each widget instance to retain build information.
inspector = []

# Use dynamic dispatch at the app-extension level.
#
# This speeds-up compilation time at the cost of runtime.
dyn_app_extension = []

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = ["zng-var/dyn_closure", "zng-app-context/dyn_closure"]

# like cfg(test) but also visible in docs and integration tests.
#
# USAGE:
#
# For zng-core maintainers, use `#[cfg(feature="test_util")]` in the helper types and places where
# the types are used. Use `do` to run integration tests.
#
# For external dependents, build with this feature to use the test helper types that show
# in the documentation.
test_util = ["multi_app", "deadlock_detection"]

# Allows multiple app instances per-process.
#
# This feature allows multiple apps, one app per thread at a time. The `LocalContext` tracks
# what app is currently running in each thread and `app_local!` statics switch to the value of each app
# depending on the current thread.
#
# Not enabled by default, but enabled by `feature="test_util"`.
multi_app = ["zng-app-context/multi_app"]

# Instrument every widget outer-most node to trace UI methods.
trace_widget = []

# Instrument every property and intrinsic node to trace UI methods.
#
# Note that this can cause very large trace files and bad performance.
trace_wgt_item = []

# Spawns a thread on app creation that checks and prints `parking_lot` deadlocks.
#
# Not enabled by default, but enabled by `feature="test_util"`.
deadlock_detection = ["zng-task/deadlock_detection"]

[dependencies]
zng-app-proc-macros = { path = "../zng-app-proc-macros", version = "0.2.0" }

zng-unique-id = { path = "../zng-unique-id", version = "0.2.0" }
zng-handle = { path = "../zng-handle", version = "0.2.0" }
zng-clone-move = { path = "../zng-clone-move", version = "0.2.0" }
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-time = { path = "../zng-time", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.0" }
zng-txt = { path = "../zng-txt", version = "0.2.0" }
zng-task = { path = "../zng-task", version = "0.2.0" }
zng-view-api = { path = "../zng-view-api", version = "0.2.0", features = ["var"] }
zng-state-map = { path = "../zng-state-map", version = "0.2.0" }
zng-layout = { path = "../zng-layout", version = "0.2.0" }
zng-color = { path = "../zng-color", version = "0.2.0" }

tracing = "0.1"
pretty-type-name = "1"
parking_lot = "0.12"
serde = "1"
bytemuck = "1"
flume = "0.11"
atomic = "0.6"
bitflags = "2"
paste = "1"
once_cell = "1"
unic-langid = { version = "0.9", features = ["serde"] }
unicase = "2"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "zng-app/doc/html-in-header.html" ]
