[package]
name = "zng-color"
version = "0.2.1"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-color"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-color-proc-macros = { path = "../zng-color-proc-macros", version = "0.2.0" }
zng-layout = { path = "../zng-layout", version = "0.2.1" }
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.1" }
zng-view-api = { path = "../zng-view-api", version = "0.2.1" }

paste = "1"
serde = "1"
