[package]
name = "zng-wgt-tooltip"
version = "0.7.8"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_tooltip"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.8.7" }
zng-wgt-layer = { path = "../zng-wgt-layer", version = "0.6.7" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.5.7" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.7.8" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.5.7" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.7.7" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.6.7" }
zng-app = { path = "../zng-app", version = "0.16.7" }
zng-ext-input = { path = "../zng-ext-input", version = "0.8.7" }
