[package]
name = "zng-wgt-rule-line"
version = "0.11.5"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_rule_line"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app = { path = "../zng-app", version = "0.21.5", default-features = false }
zng-wgt = { path = "../zng-wgt", version = "0.13.5", default-features = false }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.10.5", default-features = false }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.12.5", default-features = false }
bitflags = { version = "2.5", default-features = false, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
