[package]
name = "zng-wgt-access"
version = "0.2.19"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_access"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app = { path = "../zng-app", version = "0.8.0" }
zng-view-api = { path = "../zng-view-api", version = "0.5.4" }
zng-wgt = { path = "../zng-wgt", version = "0.4.2" }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.4.0" }
