[package]
name = "zng-wgt-data"
version = "0.6.2"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_data"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["debug_default"]

# **deprecated** enable needed features directly
debug_default = ["var_type_names"]

# Compile with var type names for error messages
var_type_names = ["zng-var/type_names"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.9.2" }
zng-color = { path = "../zng-color", version = "0.7.2" }
zng-var = { path = "../zng-var", version = "0.8.2" }

serde = { version = "1.0", features = ["derive"] }
