[package]
name = "zng-wgt-data"
version = "0.2.26"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_data"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.4.9" }
zng-color = { path = "../zng-color", version = "0.3.5" }
zng-var = { path = "../zng-var", version = "0.4.10" }

serde = { version = "1.0", features = ["derive"] }
