[package]
name = "zng-view-prebuilt"
version = "0.3.1"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_view_prebuilt"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["embedded"]

# Requires embedded on build, if prebuilt is not in './lib' and download fails the build will fail.
#
# This is enabled by default.
embedded = []

[dependencies]
libloading = "0.8"

[build-dependencies]
hashers = "1.0"
base64 = "0.22"
home = "0.5"

[package.metadata.docs.rs]
all-features = true
