[package]
name = "zng-wgt-text"
version = "0.4.13"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_text"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.4.16" }
zng-app-context = { path = "../zng-app-context", version = "0.5.9" }
zng-app = { path = "../zng-app", version = "0.11.1" }
zng-color = { path = "../zng-color", version = "0.3.11" }
zng-layout = { path = "../zng-layout", version = "0.2.26" }
zng-wgt-data = { path = "../zng-wgt-data", version = "0.2.33" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.33" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.33" }
zng-wgt-layer = { path = "../zng-wgt-layer", version = "0.3.23" }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.4.23" }
zng-ext-undo = { path = "../zng-ext-undo", version = "0.2.33" }
zng-ext-font = { path = "../zng-ext-font", version = "0.4.6" }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.5.12" }
zng-view-api = { path = "../zng-view-api", version = "0.10.0" }
zng-ext-clipboard = { path = "../zng-ext-clipboard", version = "0.2.33" }
zng-ext-input = { path = "../zng-ext-input", version = "0.5.21" }
zng-ext-window = { path = "../zng-ext-window", version = "0.3.23" }

atomic = "0.6"
tracing = "0.1"
serde = "1.0"
parking_lot = "0.12"
bitflags = { version = "2.5", features = ["serde", "bytemuck"] }
bytemuck = { version = "1.15", features = ["derive"] }
euclid = "0.22"
