[package]
name = "zng-ext-window"
version = "0.2.2"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_ext_window"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
test_util = []

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.2.1" }
zng-unique-id = { path = "../zng-unique-id", version = "0.2.1" }
zng-app-context = { path = "../zng-app-context", version = "0.2.1" }
zng-app = { path = "../zng-app", version = "0.2.2" }
zng-var = { path = "../zng-var", version = "0.2.2" }
zng-txt = { path = "../zng-txt", version = "0.2.1" }
zng-layout = { path = "../zng-layout", version = "0.2.2" }
zng-state-map = { path = "../zng-state-map", version = "0.2.1" }
zng-view-api = { path = "../zng-view-api", version = "0.2.2" }
zng-task = { path = "../zng-task", version = "0.2.2" }
zng-ext-image = { path = "../zng-ext-image", version = "0.2.2" }
zng-color = { path = "../zng-color", version = "0.2.2" }

serde = { version = "1", features = ["derive"] }
bitflags = { version = "2", features = ["serde", "bytemuck"] }
atomic = "0.6"
tracing = "0.1"
parking_lot = "0.12"
