[package]
name = "zng-ext-fs-watcher"
version = "0.2.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-ext-fs-watcher"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-app = { path = "../zng-app", version = "0.2.0" }
zng-clone-move = { path = "../zng-clone-move", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.0" }
zng-txt = { path = "../zng-txt", version = "0.2.0" }
zng-unit = { path = "../zng-unit", version = "0.2.0" }
zng-handle = { path = "../zng-handle", version = "0.2.0" }
zng-task = { path = "../zng-task", version = "0.2.0" }

walkdir = "2"
serde = "1"
tracing = "0.1"
fs4 = "0.8"
glob = "0.3"
notify = "6"
path-absolutize = "3"
atomic = "0.6"
parking_lot = "0.12"
flume = "0.11"

serde_json = { version = "1", optional = true }
toml = { version = "0.8", optional = true, features = ["preserve_order"] }
ron = { version = "0.8", optional = true, features = ["indexmap"] }
serde_yaml = { version = "0.9", optional = true }
