[package]
name = "zng-env-proc-macros"
version = "0.3.1"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_env_proc_macros"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false }

toml = { version = "0.9", default-features = false, features = ["parse"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
semver = { version = "1.0", default-features = false, features = ["serde"] }

sha2 = { version = "0.10", default-features = false }
