[package]
name = "zng-env-proc-macros"
version = "0.2.2"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_env_proc_macros"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"

toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }

sha2 = "0.10"
