[package]
name = "zng-wgt-settings"
version = "0.1.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_access"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-app = { path = "../zng-app", version = "0.8.0" }
zng-wgt = { path = "../zng-wgt", version = "0.4.2" }
zng-ext-config = { path = "../zng-ext-config", version = "0.2.19" }
zng-ext-font = { path = "../zng-ext-font", version = "0.3.15" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.3.9" }
zng-wgt-stack = { path = "../zng-wgt-stack", version = "0.3.9" }
zng-wgt-toggle = { path = "../zng-wgt-toggle", version = "0.3.9" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.2.19" }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.4.9" }
zng-wgt-text-input = { path = "../zng-wgt-text-input", version = "0.3.9" }
zng-wgt-button = { path = "../zng-wgt-button", version = "0.3.9" }
zng-wgt-rule-line = { path = "../zng-wgt-rule-line", version = "0.3.9" }
zng-wgt-style = { path = "../zng-wgt-style", version = "0.3.9" }
zng-wgt-filter = { path = "../zng-wgt-filter", version = "0.2.19" }
zng-wgt-input = { path = "../zng-wgt-input", version = "0.2.19" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.19" }
zng-wgt-fill = { path = "../zng-wgt-fill", version = "0.2.19" }
zng-wgt-markdown = { path = "../zng-wgt-markdown", version = "0.3.9" }
zng-wgt-tooltip = { path = "../zng-wgt-tooltip", version = "0.3.9" }
