[package]
name = "zng-state-map"
version = "0.8.0"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_state_map"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-unique-id = { path = "../zng-unique-id", version = "0.9.0", default-features = false }

bytemuck = { version = "1.15", default-features = false }
pretty-type-name = { version = "1.0", default-features = false }
