[package]
name = "zng-app-proc-macros"
version = "0.6.0"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_app_proc_macros"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "visit", "extra-traits", "derive"] }
quote = "1.0"
lazy_static = "1.4"

once_cell = "1.19"
unic-langid = "0.9"
fluent-syntax = "0.12"

minifier = { version = "0.3", default-features = false }
