[package]
name = "do-tasks"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
description = "Run tasks for managing this project. Implemented in \"./tools/do-tasks\"."

[dependencies]
ansi_term = "0.12"
glob = "0.3"
opener = "0.4"
regex = "1.5"

[workspace]