[package]
name = "do-tasks"
version = "0.0.0"
authors = ["The Zng Project Developers"]
edition = "2021"
description = "Run tasks for managing this project. Implemented in \"./tools/do-tasks\"."

[dependencies]
ansi_term = "0.12"
glob = "0.3"
opener = "0.6"
regex = "1"
topological-sort = "0.2"

[workspace]