name: Check All Features

on:
  workflow_dispatch:
    inputs:
      max:
        default: "2"
      clean:
        default: "60"

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings -A unused_assignments'
  RUSTDOCFLAGS: '--deny=warnings -A unused_assignments'
  CARGO_TERM_COLOR: always
  ZNG_TP_LICENSES: false

jobs:
  check-ubuntu:
    strategy:
      fail-fast: false
      matrix:
          chunk: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
          profile: ["", --release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: sudo apt-get update -o Acquire::Retries=5 && sudo apt install libfontconfig1-dev -o Acquire::Retries=5 && sudo apt install libasound2-dev -o Acquire::Retries=5
      - run: cargo do check-all-features ${{ matrix.profile }} --max ${{ github.event.inputs.max }} --clean ${{ github.event.inputs.clean }} --chunk "${{ matrix.chunk }}/12"
      - run: cargo clean
  check-macos:
    needs: [check-ubuntu]
    strategy:
      fail-fast: false
      matrix:
          chunk: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
          profile: ["", --release]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo do check-all-features ${{ matrix.profile }} --max ${{ github.event.inputs.max }} --clean ${{ github.event.inputs.clean }} --chunk "${{ matrix.chunk }}/12"
      - run: cargo clean
  check-windows:
    needs: [check-ubuntu]
    strategy:
      fail-fast: false
      matrix:
          chunk: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
          profile: ["", --release]
    runs-on: windows-latest
    env:
      CC: 'clang-cl'
      CXX: 'clang-cl'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo do check-all-features ${{ matrix.profile }} --max ${{ github.event.inputs.max }} --clean ${{ github.event.inputs.clean }} --chunk "${{ matrix.chunk }}/12"
      - run: cargo clean