name: do

on:
  workflow_dispatch:
    inputs:
      runs-on: 
        default: 'ubuntu-latest'
        required: true
      cargo-do:
        required: true
      commit-msg:
        required: false

run-name: on ${{ github.event.inputs.runs-on }} do ${{ github.event.inputs.cargo-do }}

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings -A unused_assignments'
  RUSTDOCFLAGS: '--deny=warnings -A unused_assignments'
  CARGO_TERM_COLOR: always
  ZNG_TP_LICENSES: false

jobs:
  do:
    runs-on: ${{ github.event.inputs.runs-on }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: cargo do ${{ github.event.inputs.cargo-do }}
      - if: ${{ github.event.inputs.commit-msg && github.event.inputs.commit-msg != '' }}
        name: commit all changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          git commit -m "${{ github.event.inputs.commit-msg }}"
          git push