name: Nightly Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings -A unused_assignments'
  RUSTDOCFLAGS: '--deny=warnings -A unused_assignments'
  CARGO_TERM_COLOR: always

jobs:
  check-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        feature: ['--all-features', '']
        profile: ['--release', '']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: install cargo-about
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-about
      - run: sudo apt-get update -o Acquire::Retries=5 && sudo apt install libfontconfig1-dev -o Acquire::Retries=5
      - run: cargo +nightly check --workspace ${{ matrix.feature }} ${{ matrix.profile }} 
  check-windows:
    needs: [check-ubuntu]
    strategy:
      fail-fast: false
      matrix:
        feature: ['--all-features', '']
        profile: ['--release', '']
    runs-on: windows-latest
    env:
      CC: 'clang-cl'
      CXX: 'clang-cl'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: install cargo-about
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-about
      - run: cargo +nightly check --workspace ${{ matrix.feature }} ${{ matrix.profile }}
  check-macos:
    needs: [check-ubuntu]
    strategy:
      fail-fast: false
      matrix:
        feature: ['--all-features', '']
        profile: ['--release', '']
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: install cargo-about
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-about
      - run: cargo +nightly check --workspace ${{ matrix.feature }} ${{ matrix.profile }} 
  doc:
    runs-on: ubuntu-latest
    needs: [check-ubuntu]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: install cargo-about
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-about
      - run: sudo apt-get update -o Acquire::Retries=5 && sudo apt install libfontconfig1-dev -o Acquire::Retries=5
      - run: cargo +nightly doc --all-features --no-deps