[package]
name = "examples-util"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
rustc-hash = "1"
v_jsonescape = "0.7"
parking_lot = "0.12"